### PR TITLE
Submitting new doodle stopyransky/pixeloze

### PR DESCRIPTION
**Pull request by stopyransky**
hi! My first pull request, I hope everything is ok. Please check. Cheers.
added doodles/stopyransky/pixeloze

### CODE REVIEW

**Comment by neilcarpenter** [comment]
Hey!

Seem to be missing the `p5.js` file though, could you push again with the version you're using?

Thanks :smile: :+1:

**Comment by stopyransky** [comment]
addded p5.js

**Comment by neilcarpenter** [comment]
Published now!

:boom:

http://codedoodl.es/gnw

thumb

**Comment by stopyransky** [comment]
great! :) cheers

**Pull request closed without merging**
