### PR TITLE
codebrush added

### PR DESCRIPTION
**Pull request by gwenvanhee**
Hello Neil,

Great project, hoping to be a part of it & love to get some feedback!
You contact me via twitter/github @gwenvanhee

Kind regards,
Gwen

### CODE REVIEW

**Comment by neilcarpenter** [comment]
Hey Gwen!

Thanks, and thanks for submitting!

Unfortunately I have messed the repo up a bit by removing file formats from the /`doodles` directory via `.gitignore`, forgetting that this would affect contributions via pull request.

Could you please either re-fork the repo (I have fixed the `.gitignore` issue now), or push again using `--force` to make sure your code comes through in the pull request?

Alternatively you can just submit via the [form](http://codedoodl.es/form) and link to a live version of your doodle, or another repo.

Let me know if you have any questions!

Cheers.

**Comment by gwenvanhee** [comment]
Hey Neil,

Just copy/pasted the .gitignore from your repo & pushed it to my fork.
The html-files are included in the commit now...

Thnx!
Gwen

**Comment by neilcarpenter** [comment]
Cheers! Looks great, thanks again for submitting :)

**Comment by neilcarpenter** [comment]
Uploaded now!

http://codedoodl.es/zjw

thumb

**Comment by gwenvanhee** [comment]
Great! Thnx guys!

**Pull request closed without merging**
