### PR TITLE
Racing Lines

### PR DESCRIPTION
**Pull request by raurir**
My contribution to code doodles. Thanks.

### CODE REVIEW

**Comment by neilcarpenter** [comment]
Published now!

:boom:

http://codedoodl.es/rwz

thumb

**Comment by raurir** [comment]
cool!

hmm, keyboard entry not working for me... how about you?

I guess the parent window has focus rather than the iframe.

If you can remove the instruction
" or use Arrow Keys + Enter + Space"
for the moment maybe?

Cheers,

**Comment by neilcarpenter** [comment]
Yep, you're right! iframe wasn't being automatically focused. Noticed that earlier (#18) on a previous doodle.. and have fixed now.

**Comment by raurir** [comment]
Very good. Set timeout wins again.

On Wed, Aug 19, 2015 at 8:47 am, Neil Carpenter < notifications@github.com [notifications@github.com] > wrote:
Yep, you're right! iframe wasn't being automatically focused. Noticed that
earlier ( #18 [https://github.com/fluuuid/codedoodl.es/issues/18] ) on a previous doodle.. and have fixed now.

—
Reply to this email directly or view it on GitHub
[https://github.com/fluuuid/codedoodl.es/pull/17#issuecomment-132380338] .[https://github.com/notifications/beacon/AAXY1m0QYntS3-sgYPYNVKKEqyP5BkZOks5oo62IgaJpZM4Fswhc.gif]

**Comment by raurir** [comment]
Thanks

On Wed, Aug 19, 2015 at 8:59 am, Rauri Rochford < raurir@gmail.com [raurir@gmail.com] > wrote:
Very good. Set timeout wins again.

On Wed, Aug 19, 2015 at 8:47 am, Neil Carpenter < notifications@github.com [notifications@github.com] > wrote:
Yep, you're right! iframe wasn't being automatically focused. Noticed that
earlier ( #18 [https://github.com/fluuuid/codedoodl.es/issues/18] ) on a previous doodle.. and have fixed now.

—
Reply to this email directly or view it on GitHub
[https://github.com/fluuuid/codedoodl.es/pull/17#issuecomment-132380338] .[https://github.com/notifications/beacon/AAXY1m0QYntS3-sgYPYNVKKEqyP5BkZOks5oo62IgaJpZM4Fswhc.gif]

**Comment by neilcarpenter** [comment]
haha it never fails!

**Pull request closed without merging**
